cnpj:
  outputs:
    dev:
      dataset: mds_cnpj
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: us-central1
      method: oauth
      priority: interactive
      project: infra-itaborai
      threads: 6
      type: bigquery
  target: dev
