{{config(
    materialized = 'view',
    alias = 'decred_silver',
    tags = ['decred', 'bronze'],
    )
    }}


SELECT *
FROM
(
SELECT
PA
,NU_CNPJ_CLIENTE_ORIG
,DS_OPERACAO_TIPO_NATUREZA_OK
,SUM(VL_OPERACAO) AS VL_OPERACAO
,SUM(CAST(VL_CANCELADO AS FLOAT64)) AS VL_CALCELADO
FROM {{ref('decred_bronze')}}
GROUP BY
PA
,NU_CNPJ_CLIENTE_ORIG
,DS_OPERACAO_TIPO_NATUREZA_OK
)
PIVOT
(
SUM(VL_OPERACAO) AS OP, SUM(VL_CALCELADO) AS CAN FOR DS_OPERACAO_TIPO_NATUREZA_OK IN ('Débito' AS DEBITO, 'Crédito' AS CREDITO)
)


