{{config(materialized = 'view')}}


SELECT *
FROM
(
SELECT
PA
,NU_CNPJ_CLIENTE_ORIG
,DS_OPERACAO_TIPO_NATUREZA
,SUM(VL_OPERACAO) AS VL_OPERACAO
,SUM(CAST(VL_CANCELADO AS FLOAT64)) AS VL_CALCELADO
FROM {{ref('decred_homo')}}
GROUP BY
PA
,NU_CNPJ_CLIENTE_ORIG
,DS_OPERACAO_TIPO_NATUREZA
)
PIVOT
(
SUM(VL_OPERACAO) AS OP, SUM(VL_CALCELADO) AS CAN FOR DS_OPERACAO_TIPO_NATUREZA IN ('Débito' AS DEBITO, 'Crédito' AS CREDITO)
)


